sudo: false
language: clojure
lein: lein2

cache:
  directories:
    - "$HOME/.m2"

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

install:
  - "script/bootstrap"

script:
  - "script/cibuild"
  - "script/docs"

after_script:
  - "script/after_cibuild"

addons:
  apt:
    packages:
      - texinfo
