def version = "1.0.0"
def project = "bookports"

node {
    stage "clean workspace"
    deleteDir()

    stage "checkout"
    checkout scm

    stage "build"
    sh "lein with-profile production do clean, deps, compile, ring uberjar, ring uberwar"
}
