#!/bin/bash -e

if [[ -z "${TRAVIS_BUILD_DIR}" ]]; then
    START_CWD="${PWD}"
else
    START_CWD="${TRAVIS_BUILD_DIR}"
fi

cd "${START_CWD}" || exit 1

lein spec

CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage --codecov
bash <(curl -s https://codecov.io/bash)

exit
