#!/bin/bash -e

if [[ -z "${TRAVIS_BUILD_DIR}" ]]; then
    START_CWD="${PWD}"
else
    START_CWD="${TRAVIS_BUILD_DIR}"
fi

cd "${START_CWD}" || exit 1

echo "Building.."
lein compile

echo "Testing.."
lein spec

echo "Linting.."
lein kibit

exit
